dist: xenial
language: cpp
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get -y install gcc-7 g++-7 python3-pip libspdlog-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
  - sudo pip install --upgrade pip
  - |
    cd /opt \
    && sudo wget https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz \
    && sudo tar xf ./cmake-3.14.0-Linux-x86_64.tar.gz \
    && mkdir -p ~/bin \
    && ln -s /opt/cmake-3.14.0-Linux-x86_64/bin/cmake ~/bin/cmake \
    && ln -s /opt/cmake-3.14.0-Linux-x86_64/bin/ccmake ~/bin/ccmake \
    && ln -s /opt/cmake-3.14.0-Linux-x86_64/bin/cpack ~/bin/cpack \
    && ln -s /opt/cmake-3.14.0-Linux-x86_64/bin/ctest ~/bin/ctest
  - sudo pip install conan
script:
  - cmake .
  - cmake --build . -- VERBOSE=1
  - cmake --build . --target package -- VERBOSE=1
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T lsmonitor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u0xadb:$BINTRAY_API_KEY "https://api.bintray.com/content/0xadb/otus/homework/$TRAVIS_BUILD_NUMBER/lsmonitor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
