dist: xenial
language: cpp
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get -y install gcc-7 g++-7 python3-pip libspdlog-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
  - sudo pip3 install virtualenv
script:
  - virtualenv -p python3 env
  - |
    cd env \
    && wget -nv https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz \
    && tar xf ./cmake-3.14.0-Linux-x86_64.tar.gz \
    && cd ..
  - $TRAVIS_BUILD_DIR/env/bin/cmake --version
  - $TRAVIS_BUILD_DIRenv/bin/pip3 install --upgrade pip
  - $TRAVIS_BUILD_DIRenv/bin/pip3 install conan
  - mkdir -p build && cd build
  - $TRAVIS_BUILD_DIR/env/bin/cmake --debug-output -H../ -B./
  - $TRAVIS_BUILD_DIR/env/bin/cmake --build . -- VERBOSE=1
  - $TRAVIS_BUILD_DIR/env/bin/cmake --build . --target package -- VERBOSE=1
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T lsmonitor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u0xadb:$BINTRAY_API_KEY "https://api.bintray.com/content/0xadb/otus/homework/$TRAVIS_BUILD_NUMBER/lsmonitor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
